#!/usr/bin/env bash
#**************************************
# aliases
#
# Collection of common commands as aliases.
#**************************************

# List open files (net connections) on tcp and udp
alias ls-net='lsof -a -i4 -i6 -itcp'

# Update font cache
alias fc-update='fc-cache -vf'

# List font directories
alias fc-ls='fc-list'

# Login to github docker registry: docker login ghcr.io -u <GITHUB_USERNAME> -p <GITHUB_ACCESS_TOKEN>
alias docker-github-login='echo $GIT_TOKEN | docker login ghcr.io -u $GIT_USERNAME --password-stdin'

# Tree git repo with files first, colorization, and ignore pattern.
alias tree-repo="tree -a -C -I '.git|README.md' --filesfirst"

# Generate random password
alias randpwd="openssl rand -base64 16"

# Get architecture (uname)
alias get-arch="uname -m"

# Print Kernel architecture (dpkg)
alias dpkg-arch="dpkg --print-architecture"

# Get kernel version
alias get-kernel="uname -r"

# Get OS
alias get-os="uname -o"

