#!/usr/bin/env bash
#**************************************
# helpers
#
# Collection of common bash helper functions.
#**************************************

check_if_root() {
    if [ "$(id -u)" -ne 0 ]; then
        echo -e 'Script must be run as root. Use sudo, su, or add "USER root" to your Dockerfile before running this script.'
        exit 1
    fi
}

# Get OS type
get_os_type() {
    # if [[ $OSTYPE == 'darwin'* ]]; then
    #     echo "mac"
    # else
    #     echo "other"
    # fi
    case "$OSTYPE" in
    solaris*) echo "SOLARIS" ;;
    darwin*) echo "OSX" ;;
    linux*) echo "LINUX" ;;
    bsd*) echo "BSD" ;;
    msys*) echo "WINDOWS" ;;
    cygwin*) echo "WINDOWS" ;;
    *) echo "unknown: $OSTYPE" ;;
    esac
}

# Get path to script
get_script_path() {
    local basedir=$(dirname "$0")
    echo $basedir
}

# Test
test_echo_env() {
    echo "echo "$A" "$B" "$C""
}
