#!/bin/bash 
#**************************************
# git-init 
#
# Remove old `.git`, init repo, and push to remote.
#**************************************

set -e

init(){
  local _dir="$(pwd)";
  local _baseName="$(basename $_dir)";
  local _src="${_dir}/.git";
  local _username="curol"

  local _des="https://github.com/${_username}/${_baseName}.git";

  local _purge_cmd="rm -rf "${_src}"";
  local _git_cmd="git init && git branch -M main && git add -A && git commit -m 'init' && git remote add origin "${_des}" && git push --set-upstream origin main -f";
  # local _git_config_cmd="git config user.name "${_username}" && git config user.email "${_email}""

  echo "command:";
  echo "${_purge_cmd}";
  echo "${_git_cmd}";
  echo "";
  read -p "Are you sure you want to run this command?" -n 1;
  echo "";
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    eval ${_purge_cmd}
    eval ${_git_cmd}
    echo ""
    echo "git config:"
    echo "---------------------------------------"
    git config --list | cat
    echo "---------------------------------------"
    echo ""
    echo "Finished initializing git repo."
  fi;
}